run:
  timeout: 30m

linters:
  disable-all: false
  enable:
    - bodyclose
    - errcheck
    - exportloopref
    - gosec
    - gosimple
    - ginkgolinter
    - gocritic
    - govet
    - ineffassign
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gocritic:
  staticcheck:
    checks:
      - "all"
  stylecheck:
