################################################################################
#Name:config
#Desc: Kind config for exposing port 30000 of kind cluster
#      Can access through <kind-cluster-ip>:30000 or <host-ip>:20000
###############################################################################
# cluster-config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 20000
    protocol: TCP
