##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: gwctl
    service: reviews
spec:
  ports:
  - port: 9080
    targetPort: 9080
    name: http
  selector:
    app: gwctl