################################################################
#Name: mbgctl-deployment 
#Desc: YAML file for creating mbgctl for CLI to MBG 
################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbgctl-deployment
  labels:
    app: mbgctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbgctl
  template:
    metadata:
      labels:
        app: mbgctl
    spec:
      containers:
      - name: mbgctl
        #image: gcr.io/multi-cloud-networks-4438/mbg:latest
        image: mbg
        imagePullPolicy: IfNotPresent
        command: [ "sleep" ]
        args: [ "infinity" ]  
        ports:
        - containerPort: 50051