################################################################
#Name: Haproxy-svc 
#Desc: service file for creating a load-balancer with external 
#      port 5100  
################################################################
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  type: NodePort
  selector:
    app: my-haproxy
  ports:
    - protocol: TCP
      port: 5300
      targetPort: 5300
      nodePort: 30000