################################################################
#Name: split-svc 
#Desc: service file for creating a load-balancer with external 
#      port 5100  
################################################################
apiVersion: v1
kind: Service
metadata:
  name: split-service
spec:
  #type: ClusterIP
  selector:
    app: tcp-split
  ports:
    - protocol: TCP
      port: 5300
      targetPort: 5300