################################################################
#Name: cluster-mbg-service
#Desc: service file for creating a load-balancer with external 
#      port 5000  
################################################################
apiVersion: v1
kind: Service
metadata:
  name: cluster-mbg-service
spec:
  #type: ClusterIP
  type: NodePort
  selector:
    app: cluster-mbg
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 30000
      name: grpc-port