################################################################
#Name:mbg-svc
#Desc: service file for connecting incoming traffic to cluster to 
#      mbg 
################################################################
apiVersion: v1
kind: Service
metadata:
  name: mbg-service
spec:
  type: NodePort
  selector:
    app: mbg
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30000