################################################################
#Name: mbg 
#Desc: Run mbg pod that listen to port 5002
################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbg-deployment
  labels:
    app: mbg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbg
  template:
    metadata:
      labels:
        app: mbg
    spec:
      containers:
      - name: mbg
        image: gcr.io/multi-cloud-networks-4438/mbg:latest
        imagePullPolicy: IfNotPresent
        command: [ "sleep" ]
        args: [ "infinity" ]        
        ports:
        - containerPort: 50051