################################################################
#Name: server 
#Desc: Run only server side of mbg -Not in used 
################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbg-deployment
  labels:
    app: mbg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mbg
  template:
    metadata:
      labels:
        app: mbg
    spec:
      containers:
      - name: mbg
        image: icr.io/k8s-ns/mbg
        imagePullPolicy: IfNotPresent
        command: ["/server"]
        args: ["--listen", ":5002", "--mbg",":5003"]
        ports:
        - containerPort: 5002